USE K300

CREATE DATABASE K300

CREATE TABLE USERS (
	Username VARCHAR(100) NOT NULL,
	Password VARCHAR(100),
	IsAdmin TINYINT DEFAULT 0,
	DiscountCode VARCHAR(100) DEFAULT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)
 GO


CREATE TABLE PRODUCT_CATES (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
) 

GO


CREATE TABLE PRODUCT_SIZES (
	ProductId int,
	SizeId int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
) 

GO


CREATE TABLE PRODUCT_COLORS (
	ProductId int,
	ColorId int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
) 

GO

drop table PRODUCT_COLORS

CREATE TABLE COLORS (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)

GO


CREATE TABLE BRANDS (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)

GO


CREATE TABLE SIZES (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)

GO


CREATE TABLE PRODUCTS (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	Price VARCHAR(20),
	IsPopular TINYINT DEFAULT 0,
	QuantityInStock INT,
	IsOutOfStock TINYINT DEFAULT 0,
	ProductCode VARCHAR(100),
	SizeId VARCHAR(2),
	CateId INT,
	ColorId INT,
	BrandId INT,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)

GO


CREATE TABLE INVOICES (
	Id INT IDENTITY(1,1) NOT NULL,
	TotalMonney VARCHAR(30),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)
GO


CREATE TABLE INVOICE_DETAILS (
	InvoiceId INT NOT NULL,
	ProductId INT NOT NULL,
	ProductPrice VARCHAR(30),
	Quantity INT,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)
GO


CREATE TABLE IMPORT_PRODUCTS (
	Id INT NOT NULL,
	Price VARCHAR(30),
	Quantity INT,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)
GO


CREATE TABLE DISCOUNTS (
	Id INT NOT NULL,
	DiscountCode VARCHAR(100),
	Price VARCHAR(30),
	Quantity INT,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)
GO


CREATE TABLE CARTS (
	Id INT NOT NULL,
	Username VARCHAR(100) NOT NULL,
	ProductId INT,
	ProductPrice VARCHAR(30),
	Quantity INT,
	TotalPrice VARCHAR(30),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
)
GO

CREATE TABLE PRODUCERS (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
) 

GO

CREATE TABLE IMAGES (
	Id INT IDENTITY(1,1) NOT NULL,
	Sbase64 VARCHAR(max) NOT NULL,
	ProductId int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
) 

GO

CREATE TABLE MODELS (
	Id INT IDENTITY(1,1) NOT NULL,
	Height int,
	Weight int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	UpdatedAt DATETIME,
	UpdatedBy VARCHAR(100),
	DeletedAt DATETIME,
	DeletedBy VARCHAR(100),
	IsActived TINYINT DEFAULT 1,
	IsDeleted TINYINT DEFAULT 0
) 

GO


